---
title: "Readme_Deliverable-2"
author: "Prasanthi"
date: "2026-08-02"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**README**

**Dataset Source**

This project uses the [**Inside Airbnb**](https://insideairbnb.com/get-the-data/) listings dataset for New Zealand. The dataset contains information about Airbnb listings, including listing details, host information, location, pricing, availability, and guest reviews.

**Dataset:** listings.csv

The data was downloaded from the Inside Airbnb project, which provides publicly available Airbnb data for research and analysis.

**Scrape Date:** 19^th^ of June 2026

**Dataset Columns**

+------------------------------------+------------------------+-----------------------------------------------------------------------------------------+---------------------+
| **Field**                          | Data type              | Description                                                                             | Data Range          |
+====================================+========================+=========================================================================================+=====================+
| **id**                             | Numeric (Long Integer) | Unique identifier for each Airbnb listing                                               | Eight digit         |
|                                    |                        |                                                                                         |                     |
|                                    |                        |                                                                                         | 36194 to 54409477   |
+------------------------------------+------------------------+-----------------------------------------------------------------------------------------+---------------------+
| **name**                           | String                 | Title of the Airbnb listing                                                             |                     |
+------------------------------------+------------------------+-----------------------------------------------------------------------------------------+---------------------+
| **host_id**                        | Numeric (Long Integer) | Unique identifier for the host                                                          | Nine digit integer  |
|                                    |                        |                                                                                         |                     |
|                                    |                        |                                                                                         | 29300 to 757214756  |
+------------------------------------+------------------------+-----------------------------------------------------------------------------------------+---------------------+
| **host_name**                      | String                 | Name of the host                                                                        |                     |
+------------------------------------+------------------------+-----------------------------------------------------------------------------------------+---------------------+
| **neighbourhood_group**            | String                 | City where the listing is located                                                       |                     |
+------------------------------------+------------------------+-----------------------------------------------------------------------------------------+---------------------+
| **neighbourhood**                  | String                 | Local ward of the listing                                                               |                     |
+------------------------------------+------------------------+-----------------------------------------------------------------------------------------+---------------------+
| **latitude**                       | Numeric (Float)        | Latitude coordinate of the listing                                                      | -46.907 to -34.516  |
+------------------------------------+------------------------+-----------------------------------------------------------------------------------------+---------------------+
| **longitude**                      | Numeric (Float)        | Longitude coordinate of the listing                                                     | -176.561 to 178.486 |
+------------------------------------+------------------------+-----------------------------------------------------------------------------------------+---------------------+
| **room_type**                      | String                 | Type of accommodation (Entire home/apartment, Private room, Shared room, or Hotel room) | 4                   |
+------------------------------------+------------------------+-----------------------------------------------------------------------------------------+---------------------+
| **price**                          | Numeric (Integer)      | Nightly rental price (NZD)                                                              | 5-84438             |
+------------------------------------+------------------------+-----------------------------------------------------------------------------------------+---------------------+
| **minimum_nights**                 | Numeric (Integer)      | Minimum number of nights required for a booking                                         | 1-639               |
+------------------------------------+------------------------+-----------------------------------------------------------------------------------------+---------------------+
| **number_of_reviews**              | Numeric (Integer)      | Total number of reviews received by the listing                                         | 0-1584              |
+------------------------------------+------------------------+-----------------------------------------------------------------------------------------+---------------------+
| **last_review**                    | String                 | Date of the most recent guest review                                                    | 19/06/2026          |
+------------------------------------+------------------------+-----------------------------------------------------------------------------------------+---------------------+
| **reviews_per_month**              | Numeric (Float)        | Average number of reviews received per month                                            | 0.01-24.72          |
+------------------------------------+------------------------+-----------------------------------------------------------------------------------------+---------------------+
| **calculated_host_listings_count** | Numeric (Integer)      | Number of active listings managed by the same host                                      | 1-1215              |
+------------------------------------+------------------------+-----------------------------------------------------------------------------------------+---------------------+
| **availability_365**               | Numeric (Integer)      | Number of days the listing is available for booking during the next 365 days            | 0-365               |
+------------------------------------+------------------------+-----------------------------------------------------------------------------------------+---------------------+
| **number_of_reviews_ltm**          | Numeric (Integer)      | Number of reviews received during the last 12 months                                    | 0-267               |
+------------------------------------+------------------------+-----------------------------------------------------------------------------------------+---------------------+
| **license**                        | String                 | Registration or licence number                                                          | Not Available       |
+------------------------------------+------------------------+-----------------------------------------------------------------------------------------+---------------------+

N.B.:

• Each row represents a single Airbnb listing.

• Missing values occur in columns last_review, reviews_per_month, and license.

Date Formatting: Single digit dates were formatted in MS Excel (i.e. d/mm/yyyy to dd/mm/yyyy)

Data cleaning: Using the Missing Value (Cleaning) node, Treatment by Column function

+--------------------------------+----------------------+---------------------------------------------------------------------+
|                                |                      |                                                                     |
+================================+======================+=====================================================================+
| **Field / Column**             | **Treatment**        | **Rationale**                                                       |
+--------------------------------+----------------------+---------------------------------------------------------------------+
| Id                             | Do nothing           | No missing Data                                                     |
+--------------------------------+----------------------+---------------------------------------------------------------------+
| name                           | Do nothing           | No missing Data                                                     |
+--------------------------------+----------------------+---------------------------------------------------------------------+
| host_id                        | Do nothing           | No missing Data                                                     |
+--------------------------------+----------------------+---------------------------------------------------------------------+
| host_name                      | Do nothing           | No missing Data                                                     |
+--------------------------------+----------------------+---------------------------------------------------------------------+
| neighbourhood_group            | Remove Row\*         | No missing data                                                     |
|                                |                      |                                                                     |
|                                |                      | Used for analysis, missing data resulted in removal of entire row   |
+--------------------------------+----------------------+---------------------------------------------------------------------+
| neighbourhood                  | Do nothing           | No missing data                                                     |
+--------------------------------+----------------------+---------------------------------------------------------------------+
| latitude                       | Do nothing           | No missing Data                                                     |
+--------------------------------+----------------------+---------------------------------------------------------------------+
| longitude                      | Do nothing           | No missing Data                                                     |
+--------------------------------+----------------------+---------------------------------------------------------------------+
| room_type                      | Do nothing           | No missing Data                                                     |
+--------------------------------+----------------------+---------------------------------------------------------------------+
| price                          | Remove Row\*         | Used for analysis, missing data resulted in removal of entire row   |
+--------------------------------+----------------------+---------------------------------------------------------------------+
| minimum_nights                 | Do nothing           | No missing Data                                                     |
+--------------------------------+----------------------+---------------------------------------------------------------------+
| number_of_reviews              | Remove Row\*         | No missing Data                                                     |
|                                |                      |                                                                     |
|                                |                      | Used for analysis, missing data resulted in removal of entire row   |
+--------------------------------+----------------------+---------------------------------------------------------------------+
| last_review                    | Remove Row\*         | Used for analysis, missing data resulted in removal of entire row   |
+--------------------------------+----------------------+---------------------------------------------------------------------+
| reviews_per_month              | Do nothing           | Missing Data, not applicable for data analysis                      |
+--------------------------------+----------------------+---------------------------------------------------------------------+
| calculated_host_listings_count | Do nothing           | Missing Data, not applicable for data analysis                      |
+--------------------------------+----------------------+---------------------------------------------------------------------+
| availability_365               | Do nothing           | No missing Data                                                     |
+--------------------------------+----------------------+---------------------------------------------------------------------+
| number_of_reviews_ltm          | Do nothing           | No missing Data                                                     |
+--------------------------------+----------------------+---------------------------------------------------------------------+
| license                        | Do nothing           | Not available                                                       |
+--------------------------------+----------------------+---------------------------------------------------------------------+
